import { app, BrowserWindow } from 'electron';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

// === Spawn Django backend (Windows + macOS friendly) ===
import { spawn } from 'child_process';
import path from 'path';
import fs from 'fs';

let djangoProcess: ReturnType<typeof spawn> | null = null;

/** Resolve backend root: app is in frontend/AuggieTaskManagerFrontend, repo root is two levels up, backend at repo/backend/auggietaskmanager. */
const getBackendRoot = (): string => {
  const appRoot = app.getAppPath();
  return path.resolve(appRoot, '..', '..', 'backend', 'auggietaskmanager');
};

/** Prefer venv Python; fall back to python3 (macOS) or python (Windows). */
const getPythonExecutable = (backendRoot: string): string => {
  const venvDir = path.resolve(backendRoot, '..', 'venv');
  if (process.platform === 'win32') {
    const venvPython = path.join(venvDir, 'Scripts', 'python.exe');
    if (fs.existsSync(venvPython)) return venvPython;
    return 'python';
  }
  const venvPython = path.join(venvDir, 'bin', 'python');
  if (fs.existsSync(venvPython)) return venvPython;
  return 'python3';
};

const startDjango = (): void => {
  const backendRoot = getBackendRoot();
  const managePy = path.join(backendRoot, 'manage.py');

  if (!fs.existsSync(managePy)) {
    console.error(`Django not found at ${managePy}`);
    return;
  }

  const pythonExe = getPythonExecutable(backendRoot);
  djangoProcess = spawn(pythonExe, [managePy, 'runserver'], {
    cwd: backendRoot,
    shell: false,
    stdio: ['ignore', 'pipe', 'pipe'],
    env: { ...process.env, PYTHONUNBUFFERED: '1' },
  });

  djangoProcess.stdout?.on('data', (data: Buffer) => {
    console.log(`Django: ${data.toString()}`);
  });

  // Django sends some normal messages to stderr (e.g. "Watching for file changes with StatReloader"), so log as info.
  djangoProcess.stderr?.on('data', (data: Buffer) => {
    console.log(`Django: ${data.toString()}`);
  });

  djangoProcess.on('close', (code) => {
    console.log(`Django process exited with code ${code}`);
  });
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

// === Electron app events ===
app.on('ready', () => {
  startDjango();
  createWindow();
});

// Quit when all windows are closed (except on macOS; there the app stays open until Cmd+Q).
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

// Stop Django when the app quits (Windows: on window close; macOS: on Cmd+Q / Quit).
app.on('before-quit', () => {
  if (djangoProcess) {
    djangoProcess.kill();
    djangoProcess = null;
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

