# Generated by Django 5.2.11 on 2026-04-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0002_alter_task_options_task_course_task_external_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('courseID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('professor', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
