# Generated by Django 5.2.11 on 2026-04-06 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_rename_related_courses_studygroup_related_course'),
        ('moodle', '0003_courses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
    ]
