# Generated by Django 5.2.11 on 2026-04-08 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0004_rename_courses_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='semester',
            field=models.CharField(blank=True, choices=[('Spring', 'Spring'), ('Fall', 'Fall')], max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseID',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moodle.course'),
        ),
    ]
