# Generated by Django 5.2.11 on 2026-03-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="moodle_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]

