# Generated by Django 5.2.11 on 2026-04-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('moodle', '0003_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroup',
            name='id',
        ),
        migrations.AddField(
            model_name='studygroup',
            name='groupID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='study_groups/'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='related_courses',
            field=models.ManyToManyField(related_name='study_groups', to='moodle.courses'),
        ),
    ]
