# Generated by Django 5.2.11 on 2026-04-06 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_remove_studygroup_id_studygroup_groupid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studygroup',
            old_name='related_courses',
            new_name='related_course',
        ),
    ]
